// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// matching_group
List matching_group(const arma::mat& X, const arma::ivec& Treat, int zeroindex);
RcppExport SEXP blopmatch_matching_group(SEXP XSEXP, SEXP TreatSEXP, SEXP zeroindexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type Treat(TreatSEXP);
    Rcpp::traits::input_parameter< int >::type zeroindex(zeroindexSEXP);
    rcpp_result_gen = Rcpp::wrap(matching_group(X, Treat, zeroindex));
    return rcpp_result_gen;
END_RCPP
}
// generalized_norm
arma::mat generalized_norm(const arma::mat& X, const arma::mat& W, double p);
RcppExport SEXP blopmatch_generalized_norm(SEXP XSEXP, SEXP WSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(generalized_norm(X, W, p));
    return rcpp_result_gen;
END_RCPP
}
