# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Finds matching group
#' @template mat
#' @templateVar X 1
#' @templateVar Treat 1
#' @param zeroindex Integer scalar. Added to the resulting index.
#' @return A list of length \eqn{n} specifying for each i to which individuals
#' each j != i will be matched.
#' @export 
#' 
#' @examples
#' # Asigning matching groups for lalonde
#' 
#' data(lalonde, package = "MatchIt")
#' dat <- lalonde
#' 
#' # Match (no exact)
#' m_noexact <- matching_group(cbind(rep(1, nrow(dat))), dat$treat)
#' 
#' # How many matches?
#' table(sapply(m_noexact, length))
#' table(dat$treat)
#' 
#' # What if we ask exact match on black
#' 
#' m_exact <- matching_group(
#'   as.matrix(dat[,"black",drop=FALSE]),
#'   dat$treat)
#' 
#' table(sapply(m_exact, length))
#' with(dat, table(treat, black))
matching_group <- function(X, Treat, zeroindex = 1L) {
    .Call('blopmatch_matching_group', PACKAGE = 'blopmatch', X, Treat, zeroindex)
}

#' Computes Quadratic Form Distance
#' @template mat
#' @templateVar X 1
#' @templateVar W 1
#' @param p Numeric scalar.
#' @export
#' 
#' 
generalized_norm <- function(X, W, p = 1.0) {
    .Call('blopmatch_generalized_norm', PACKAGE = 'blopmatch', X, W, p)
}

